"""empty message

Revision ID: 0b8f4d94272c
Revises: 
Create Date: 2024-11-23 00:39:50.487505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8f4d94272c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincodes',
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('pincode')
    )
    op.create_table('departments',
    sa.Column('Dcode', sa.Integer(), nullable=False),
    sa.Column('Dname', sa.String(length=100), nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('Dadd', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pincode'], ['pincodes.pincode'], ),
    sa.PrimaryKeyConstraint('Dcode')
    )
    op.create_table('colleges',
    sa.Column('Cid', sa.Integer(), nullable=False),
    sa.Column('Cname', sa.String(length=255), nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('Dcode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Dcode'], ['departments.Dcode'], ),
    sa.ForeignKeyConstraint(['pincode'], ['pincodes.pincode'], ),
    sa.PrimaryKeyConstraint('Cid')
    )
    op.create_table('courses',
    sa.Column('Coid', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('Coname', sa.String(length=255), nullable=False),
    sa.Column('Dcode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Dcode'], ['departments.Dcode'], ),
    sa.PrimaryKeyConstraint('Coid')
    )
    op.create_table('dphones',
    sa.Column('Dcode', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['Dcode'], ['departments.Dcode'], ),
    sa.PrimaryKeyConstraint('Dcode', 'phone')
    )
    op.create_table('classrooms',
    sa.Column('C_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.Cid'], ),
    sa.PrimaryKeyConstraint('C_id')
    )
    op.create_table('cphones',
    sa.Column('Cid', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['Cid'], ['colleges.Cid'], ),
    sa.PrimaryKeyConstraint('Cid', 'phone')
    )
    op.create_table('instructors',
    sa.Column('Iid', sa.Integer(), nullable=False),
    sa.Column('Irank', sa.String(length=100), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=False),
    sa.Column('mname', sa.String(length=100), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('Ioffice', sa.String(length=20), nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('Cid', sa.Integer(), nullable=True),
    sa.Column('Dcode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Cid'], ['colleges.Cid'], ),
    sa.ForeignKeyConstraint(['Dcode'], ['departments.Dcode'], ),
    sa.ForeignKeyConstraint(['pincode'], ['pincodes.pincode'], ),
    sa.PrimaryKeyConstraint('Iid')
    )
    op.create_table('chairmans',
    sa.Column('Dcode', sa.Integer(), nullable=False),
    sa.Column('Iid', sa.Integer(), nullable=False),
    sa.Column('CstartDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['Dcode'], ['departments.Dcode'], ),
    sa.ForeignKeyConstraint(['Iid'], ['instructors.Iid'], ),
    sa.PrimaryKeyConstraint('Dcode', 'Iid')
    )
    op.create_table('deans',
    sa.Column('Cid', sa.Integer(), nullable=False),
    sa.Column('Iid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cid'], ['colleges.Cid'], ),
    sa.ForeignKeyConstraint(['Iid'], ['instructors.Iid'], ),
    sa.PrimaryKeyConstraint('Cid', 'Iid')
    )
    op.create_table('iphones',
    sa.Column('Iid', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['Iid'], ['instructors.Iid'], ),
    sa.PrimaryKeyConstraint('Iid', 'phone')
    )
    op.create_table('sections',
    sa.Column('secid', sa.Integer(), nullable=False),
    sa.Column('sem', sa.String(length=20), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('ClassRoom_id', sa.Integer(), nullable=True),
    sa.Column('Course_id', sa.Integer(), nullable=True),
    sa.Column('Iid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ClassRoom_id'], ['classrooms.C_id'], ),
    sa.ForeignKeyConstraint(['Course_id'], ['courses.Coid'], ),
    sa.ForeignKeyConstraint(['Iid'], ['instructors.Iid'], ),
    sa.PrimaryKeyConstraint('secid')
    )
    op.create_table('students',
    sa.Column('Sid', sa.Integer(), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=False),
    sa.Column('Mname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('landmark', sa.String(length=100), nullable=True),
    sa.Column('major', sa.String(length=50), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('sec_id', sa.Integer(), nullable=True),
    sa.Column('Dcode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Dcode'], ['departments.Dcode'], ),
    sa.ForeignKeyConstraint(['pincode'], ['pincodes.pincode'], ),
    sa.ForeignKeyConstraint(['sec_id'], ['sections.secid'], ),
    sa.PrimaryKeyConstraint('Sid')
    )
    op.create_table('results',
    sa.Column('Sid', sa.Integer(), nullable=False),
    sa.Column('Coid', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Coid'], ['courses.Coid'], ),
    sa.ForeignKeyConstraint(['Sid'], ['students.Sid'], ),
    sa.PrimaryKeyConstraint('Sid', 'Coid')
    )
    op.create_table('sphones',
    sa.Column('Sid', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['Sid'], ['students.Sid'], ),
    sa.PrimaryKeyConstraint('Sid', 'phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sphones')
    op.drop_table('results')
    op.drop_table('students')
    op.drop_table('sections')
    op.drop_table('iphones')
    op.drop_table('deans')
    op.drop_table('chairmans')
    op.drop_table('instructors')
    op.drop_table('cphones')
    op.drop_table('classrooms')
    op.drop_table('dphones')
    op.drop_table('courses')
    op.drop_table('colleges')
    op.drop_table('departments')
    op.drop_table('pincodes')
    # ### end Alembic commands ###
